services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sports-store-backend
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - sports-net
    expose:
      - "8080"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: sports-store-frontend
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - sports-net
    environment:
      - API_URL=http://backend:8080

networks:
  sports-net:
    driver: bridge